'use strict';
(() => {
  const D=JSON.parse(document.getElementById('workshop-data').textContent), R=D.resources;
  const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const goodURL=u=>{try{return new URL(u).protocol==='https:';}catch{return false;}};
  const external=(u,t)=>goodURL(u)?`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(t)} ↗</a>`:esc(t);
  const sourceMap=Object.fromEntries(D.sources.map(s=>[s.id,s]));
  const sourceLink=(id,title)=>{const s=sourceMap[id];return s?external(s.url,title||s.title):'Reference unavailable';};
  const S={view:'session',slide:1,guide:'start',artifact:'collection',lens:'All',query:'',kit:'Builder',readAll:false,group:'starting',panels:{job:'task',readme:'before',presence:'about',sharing:'confirmed'}};
  const dialog=$('#dialog');let opener=null,noticeTimeout;
  function notify(text){const n=$('#notification');n.textContent=text;n.hidden=false;clearTimeout(noticeTimeout);noticeTimeout=setTimeout(()=>n.hidden=true,5000);}
  function secureLinks(root=document){$$('a[href]',root).forEach(a=>{if(/^https:\/\//.test(a.getAttribute('href'))){a.target='_blank';a.rel='noopener noreferrer';}});}
  function openDialog(title,body){if(!dialog.open)opener=document.activeElement;$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;if(!dialog.open)dialog.showModal();dialog.scrollTop=0;$('.dialog-close').focus();secureLinks(dialog);}
  function closeDialog(){if(dialog.open)dialog.close();}
  dialog.addEventListener('close',()=>{if(opener?.isConnected)opener.focus({preventScroll:true});else $('#main').focus({preventScroll:true});opener=null;});
  dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();});
  function download(text,name,type='text/markdown;charset=utf-8'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),15000);}
  function openText(title,text,name){openDialog(title,`<label class="sr-only" for="copy-text">Text to copy or save</label><textarea id="copy-text" readonly>${esc(text)}</textarea><div class="buttonrow"><button class="button" data-action="copy-text">Copy text</button><button class="button secondary" data-save-text="${esc(name)}">Save Markdown</button></div><p class="small">Edit the text to fit your own work before using it. This page does not send it anywhere.</p>`);}
  async function copyText(){const input=$('#copy-text');if(!input)return;try{await navigator.clipboard.writeText(input.value);notify('Copied.');}catch{input.focus();input.select();notify('The text is selected. Use your keyboard to copy it, or save the Markdown file.');}}
  function setSlide(n,writeHash=true){n=Math.max(1,Math.min(D.session.length,Math.floor(Number(n)||1)));S.slide=n;$$('.slide').forEach(el=>el.hidden=!S.readAll&&Number(el.dataset.scene)!==n);$('#slide-count').textContent=`${String(n).padStart(2,'0')} / ${D.session.length}`;$('#slide-progress').style.width=(100*n/D.session.length)+'%';$('#previous').disabled=n===1;$('#next').disabled=n===D.session.length;const theme=D.session[n-1].theme;$$('#chapter-nav button').forEach(b=>b.dataset.theme===theme?b.setAttribute('aria-current','step'):b.removeAttribute('aria-current'));if(writeHash){pushHash('session',String(n));if(S.readAll)$(`[data-scene="${n}"]`).scrollIntoView();else window.scrollTo(0,0);$('#main').focus({preventScroll:true});}}
  function pushHash(view,sub){const hash='#'+view+(sub?'/'+encodeURIComponent(sub):'');try{if(location.hash!==hash)history.pushState(null,'',hash);}catch{location.hash=hash;}}
  function applyView(view,sub,focus=true){if(!['session','work','guide','artifact'].includes(view))view='session';S.view=view;['session','work','guide','artifact'].forEach(v=>$(`#${v}-view`).hidden=v!==view);$$('.mainnav button').forEach(b=>{const selected=b.dataset.view===view||(b.dataset.artifact&&view==='artifact');selected?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current');});if(view==='session')setSlide(sub||S.slide,false);if(view==='work'){S.group=['starting','existing','showcase','all'].includes(sub)?sub:S.group;renderRoutes();}if(view==='guide'){S.guide=D.guides[sub]?sub:S.guide;renderGuide();}if(view==='artifact'){S.artifact=['collection','writing','readings'].includes(sub)?sub:S.artifact;renderArtifact();}if(focus){window.scrollTo(0,0);$('#main').focus({preventScroll:true});}}
  function navigate(view,sub){closeDialog();applyView(view,sub);pushHash(view,sub);}
  function readHash(){const [view,raw]=location.hash.slice(1).split('/');let sub='';try{sub=decodeURIComponent(raw||'');}catch{}applyView(view||document.body.dataset.default||'session',sub,false);}
  const panelContent={
    job:{
      task:`<h2>What would the person actually do?</h2><p>Figma’s internship connects analysis to product decisions. SQL and statistics matter because of the questions the team is trying to answer.</p><div class="question-callout">What would you need to learn to turn a finding into a useful recommendation?</div>`,
      bridge:`<div class="bridge-step"><b>Where you are</b><p>You have explored datasets in class.</p></div><div class="bridge-step"><b>What you want to practice</b><p>Deciding how to measure whether a product feature is useful.</p></div><div class="bridge-step"><b>A smaller starting point</b><p>Choose a familiar product. Compare two possible success measures and explain what each would miss.</p></div><p class="small">This is our practice suggestion, not an assignment from Figma. Suitable data can come later.</p>`
    },
    readme:{
      before:`<h2>Product analytics project</h2><p>I made a product analytics plan and compared some metrics. I want to use SQL and Python to study user behavior.</p><p>This project will show my data science skills.</p>`,
      after:`<h2>How should a team measure feature adoption?</h2><p><b>Question:</b> Which measures would show whether people find a new feature useful?</p><p><b>Approach and contribution:</b> I compared first use and repeat use as possible measures, then explained the data and assumptions each would require.</p><p><b>Current progress:</b> The brief is complete; the analysis is not. I need suitable data before I can evaluate either measure.</p>`
    },
    presence:{
      about:`<div class="presence-grid"><article><h2>About you</h2><p>Introduce your studies, interests, and the kind of work you are exploring.</p><p class="small">A short bio can be enough. A longer About section is another option.</p></article><article><h2>Selected work</h2><p>Give each project a clear title, your contribution, and a useful next click.</p><p class="small">You can include analysis, research, writing, demos, and collaborative work.</p></article><article><h2>Ways to connect</h2><p>Link to LinkedIn, a contact channel, and a public-safe résumé when useful.</p><p class="small">Check the links and remove personal details you do not want public.</p></article></div>`,
      github:`<div class="presence-grid"><article><h2>Your profile</h2><p>A bio introduces you. Pinned projects help visitors find selected work.</p></article><article><h2>A profile README</h2><p>A public repository matching your username can display a richer introduction.</p><button class="textbutton" data-guide="github">See the setup steps →</button></article><article><h2>A project README</h2><p>Explain this project: its question, your contribution, and its results or current progress.</p><button class="textbutton" data-route="readme">Improve an explanation →</button></article></div><p class="small">The profile README is an option. Your page does not need to look like anyone else’s.</p>`,
      website:`<div class="website-grid"><article><h2>GitHub Pages</h2><p>Make a separate website from files in a repository.</p></article><article><h2>Wix</h2><p>Use a visual builder and portfolio templates.</p></article><article><h2>Squarespace</h2><p>Organize project pages in a designed website.</p></article><article><h2>Build your own</h2><p>Create a custom site and choose where to host it.</p></article></div><p class="small">A separate website is optional. Compare costs, upkeep, and publishing terms in the field guide.</p>`
    },
    sharing:{
      confirmed:`<p class="message-example">“Thank you for making time to speak with me. I have been working on a project about how people start using a new product, and I thought it might provide context for my questions about product analytics. There is no need to read it beforehand, but here is a short project description: [link].”</p><p class="message-framework">Use the real meeting context, describe one relevant project, and make the link optional.</p>`,
      outreach:`<p class="message-example">“I noticed that you work in sports analytics. I’m a data science student exploring questions about player performance, and I was excited to find someone doing related work professionally. Would you be open to a brief conversation about what your work looks like day to day?”</p><p class="message-framework">Name a genuine connection, explain your interest, and make a considerate request.</p>`,
      post:`<p class="message-example">“After finishing a class analysis, I realized my chart needed more context for someone who had not worked with the data. I revised the title and caption, then asked a classmate what they understood. Here are the two versions and what I changed: [link].”</p><p class="message-framework">Explain what prompted the work, one decision or finding, and what you learned. Use only details that are true for you.</p>`
    }
  };
  function renderPanel(id){const content=panelContent[id];if(!content)return;const key=content[S.panels[id]]?S.panels[id]:Object.keys(content)[0];S.panels[id]=key;$(`#${id}-example`).innerHTML=content[key];$$(`[data-panel="${id}"]`).forEach(b=>b.setAttribute('aria-pressed',b.dataset.value===key));secureLinks($(`#${id}-example`));}
  function renderRoutes(){const groupNames={starting:'Find a starting point',existing:'Improve what you have',showcase:'Showcase your work',all:'All activities'};$('#work-filters').innerHTML=Object.entries(groupNames).map(([k,t])=>`<button data-work="${k}" aria-pressed="${S.group===k}">${t}</button>`).join('');const routes=R.routes.filter(r=>S.group==='all'||r.group===S.group);$('#route-grid').innerHTML=routes.map(r=>`<article class="route-card"><h2>${esc(r.title)}</h2><p>${esc(r.why)}</p><button class="button secondary" data-route="${r.id}">Open the activity</button></article>`).join('');$('#route-summary').textContent=`${routes.length} activities. Choose one, or use the time for a question about your own work.`;}
  function openRoute(id){const r=R.routes.find(r=>r.id===id);if(!r)return;openDialog(r.title,`<p>${esc(r.why)}</p><p><b>Where to work:</b> ${esc(r.where)}</p><ol class="dialog-steps">${r.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><p class="task-card"><b>Something to aim for:</b> ${esc(r.done)}</p><p class="small">${esc(r.fallback)}</p><div class="buttonrow"><button class="button" data-template="${r.template}">Get an outline</button><button class="button secondary" data-prompt="${r.prompt}">Optional AI prompt</button></div><div class="dialog-section"><h3>Useful references</h3>${r.refs.map(id=>`<p class="small">${sourceLink(id)}</p>`).join('')}${r.id==='website'?'<button class="textbutton" data-guide="platforms">Compare platforms →</button>':''}</div>`);}
  const guideNames={start:'Ways to get started',projects:'Choose your projects',explaining:'Explain your work',github:'GitHub features',platforms:'Portfolio platforms',permissions:'Decide what you can share',writing:'Introduce your work',tools:'AI and student resources',sources:'Sources and dates',about:'About this resource'};
  function renderGuide(){if(!D.guides[S.guide])S.guide='start';$('#guide-nav').innerHTML=Object.entries(guideNames).map(([k,v])=>`<button data-guide="${k}" ${k===S.guide?'aria-current="page"':''}>${v}</button>`).join('');$('#guide-content').innerHTML=D.guides[S.guide].html;if(S.guide==='tools')$('#guide-content').insertAdjacentHTML('beforeend',`<div class="prompt-list">${[['coach','Ask for coaching'],['critic','Request a README critique'],['coding','Understand a coding change'],['pulse','Test your understanding']].map(([id,t])=>`<button class="button secondary" data-prompt="${id}">${t}</button>`).join('')}</div>`);if(S.guide==='sources')renderSources();$('#guide-content').insertAdjacentHTML('beforeend','<div class="guide-links"><button class="button secondary" data-action="return">Return to the session</button><button class="textbutton" data-action="export-guide">Save the complete Markdown guide</button></div>');wrapTables($('#guide-content'));secureLinks($('#guide-content'));}
  function renderSources(){const q=($('#source-search')?.value||'').toLowerCase();const list=D.sources.filter(s=>`${s.title} ${s.publisher} ${s.note}`.toLowerCase().includes(q));$('#source-results').innerHTML=`<p class="result-count" role="status">${list.length} references</p>`+list.map(s=>`<article class="source-entry"><p class="source-meta">${esc(s.publisher)} · ${esc(s.checked)}</p><h3>${external(s.url,s.title)}</h3><p>${esc(s.note)}</p></article>`).join('');}
  function wrapTables(root){$$('table',root).forEach(t=>{if(t.parentElement.classList.contains('table-scroll'))return;const wrap=document.createElement('div');wrap.className='table-scroll';wrap.tabIndex=0;wrap.setAttribute('role','region');wrap.setAttribute('aria-label','Scrollable reference table');t.before(wrap);wrap.append(t);});}
  function renderArtifact(){
    $$('.artifact-tabs button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.artifact===S.artifact));const el=$('#artifact-content');
    if(S.artifact==='collection'){el.innerHTML=`<p class="lead">The five perspectives are ways to examine a portfolio, not permanent types you must choose between. This collection includes student-era work and established practitioners; each card explains the distinction.</p><div class="lens-filters" aria-label="Filter by perspective">${['All','Builder','Storyteller','Expert','Researcher','Analyst'].map(x=>`<button data-lens="${x}" aria-pressed="${S.lens===x}">${x}</button>`).join('')}</div><label class="searchfield">Search names, projects, or topics<input id="portfolio-search" type="search" value="${esc(S.query)}" placeholder="For example: music, research, dashboards"></label><div id="portfolio-results"></div>`;renderPortfolios();}
    if(S.artifact==='writing'){el.innerHTML=`<p class="lead">Choose the kind of explanation your reader needs. Each guide keeps the original Artifact’s six-part structure, with questions you can answer from your own evidence.</p><div class="writing-layout"><nav class="writing-nav" aria-label="Writing perspectives">${R.writing_guides.map(g=>`<button data-kit="${g.lens}" aria-pressed="${S.kit===g.lens}">${g.lens}</button>`).join('')}</nav><article id="writing-paper" class="writing-paper"></article></div>`;renderKit();}
    if(S.artifact==='readings'){el.innerHTML=`<p class="lead">These nine selections come from the original Artifact writing kit. Read for the author’s explanatory choices, not for a promise that your project will produce the same career outcome.</p><div class="collection-grid">${R.readings.map(r=>`<article class="reading-card"><p class="eyebrow">${esc(r.lens)}</p><h2>${esc(r.title)}</h2><p>${esc(r.note)}</p><p class="small">${esc(r.status)}</p>${external(r.url,'Read the example')}</article>`).join('')}</div>`;}
  }
  function renderPortfolios(){const q=S.query.toLowerCase();const ps=R.portfolios.filter(p=>(S.lens==='All'||p.lens===S.lens)&&`${p.name} ${p.summary} ${p.projects.join(' ')}`.toLowerCase().includes(q));$('#portfolio-results').innerHTML=`<p class="result-count" role="status">${ps.length} of ${R.portfolios.length} original selections</p><div class="collection-grid">${ps.map(p=>`<button class="portfolio-card" data-portfolio="${p.id}" aria-label="Explore ${esc(p.name)}"><span class="eyebrow">The ${esc(p.lens)}</span><h2>${esc(p.name)}</h2><p class="stage-label">${esc(p.stage)}</p><p>${esc(p.summary)}</p><span class="card-action">Explore the example →</span></button>`).join('')}</div>${ps.length?'':'<p class="no-results">No matches. Try a broader word or choose All.</p>'}`;}
  function openPortfolio(id){const p=R.portfolios.find(p=>p.id===id);if(!p)return;openDialog(p.name,`<p class="eyebrow">The ${esc(p.lens)}</p><p class="small">${esc(p.stage)}</p><p class="lead">${esc(p.summary)}</p><h3>What to look for</h3><p>${esc(p.pattern)}</p><h3>Places to begin</h3><ul>${p.projects.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><p>${external(p.url,'Visit the portfolio or repository')}</p><div class="dialog-section"><p class="small">${esc(p.note)}</p><p class="small">${esc(p.origin)} Reviewed ${esc(p.checked)}.</p><button class="button secondary" data-kit-link="${p.lens}">Open this writing guide</button></div>`);}
  function renderKit(){const g=R.writing_guides.find(x=>x.lens===S.kit)||R.writing_guides[0];$('#writing-paper').innerHTML=`<p class="eyebrow">For ${esc(g.audience.toLowerCase())}</p><h2>${esc(g.title)}</h2><p>${esc(g.description)}</p><div class="table-scroll" tabindex="0" role="region" aria-label="Writing guide structure"><table><thead><tr><th>Section</th><th>What to include</th><th>How it helps the reader</th></tr></thead><tbody>${g.rows.map(r=>`<tr><td>${esc(r.section)}</td><td>${esc(r.include)}</td><td>${esc(r.reason)}</td></tr>`).join('')}</tbody></table></div><div class="buttonrow"><button class="button" data-kit-template="${g.lens}">Get the Markdown outline</button><button class="textbutton" data-artifact="readings">Browse writing examples →</button></div><p class="small" style="margin-top:18px">${esc(g.origin)}</p>`;$$('[data-kit]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.kit===S.kit));}
  function contents(){openDialog('Contents', [...new Set(D.session.map(s=>s.theme))].map(t=>`<section class="contents-group"><h3>${esc(t)}</h3>${D.session.filter(s=>s.theme===t).map(s=>`<button data-jump="${s.number}"><span>${String(s.number).padStart(2,'0')}</span>${esc(s.title)}</button>`).join('')}</section>`).join(''));}
  document.addEventListener('click',e=>{
    const b=e.target.closest('button');if(!b)return;
    if(b.dataset.view)return navigate(b.dataset.view);
    if(b.dataset.jump)return navigate('session',b.dataset.jump);
    if(b.dataset.guide)return navigate('guide',b.dataset.guide);
    if(b.dataset.artifact)return navigate('artifact',b.dataset.artifact);
    if(b.dataset.work)return navigate('work',b.dataset.work);
    if(b.dataset.route)return openRoute(b.dataset.route);
    if(b.dataset.panel){S.panels[b.dataset.panel]=b.dataset.value;return renderPanel(b.dataset.panel);}
    if(b.dataset.lens){S.lens=b.dataset.lens;$$('[data-lens]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.lens===S.lens));return renderPortfolios();}
    if(b.dataset.portfolio)return openPortfolio(b.dataset.portfolio);
    if(b.dataset.kit){S.kit=b.dataset.kit;return renderKit();}
    if(b.dataset.kitLink){S.kit=b.dataset.kitLink;return navigate('artifact','writing');}
    if(b.dataset.kitTemplate){const g=R.writing_guides.find(x=>x.lens===b.dataset.kitTemplate);return openText(g.title,g.template,`${g.lens.toLowerCase()}-outline.md`);}
    if(b.dataset.template&&R.templates[b.dataset.template])return openText('Project outline',R.templates[b.dataset.template],`${b.dataset.template}-outline.md`);
    if(b.dataset.prompt&&R.prompts[b.dataset.prompt])return openText('Optional AI prompt',R.prompts[b.dataset.prompt],`${b.dataset.prompt}-prompt.md`);
    if(b.dataset.saveText)return download($('#copy-text').value,b.dataset.saveText);
    if(b.dataset.pdf){const p=D.printables[b.dataset.pdf];if(p){const bytes=Uint8Array.from(atob(p.base64),c=>c.charCodeAt(0));download(bytes,p.name,'application/pdf');}return;}
    const action=b.dataset.action;
    if(action==='close')closeDialog();
    if(action==='return')navigate('session',String(S.slide));
    if(action==='contents')contents();
    if(action==='copy-text')copyText();
    if(action==='export-guide')download(D.fieldMarkdown,'github-portfolios-field-guide.md');
    if(action==='read-all'){S.readAll=!S.readAll;document.body.classList.toggle('read-all',S.readAll);b.setAttribute('aria-pressed',S.readAll);b.textContent=S.readAll?'Slide view':'Read all';setSlide(S.slide,false);}
    if(action==='fullscreen'){if(document.fullscreenElement){document.exitFullscreen?.().catch(()=>{});}else if(document.documentElement.requestFullscreen){document.documentElement.requestFullscreen().catch(()=>notify('Use your browser’s full-screen control.'));}else notify('Use your browser’s full-screen control.');}
  });
  document.addEventListener('input',e=>{if(e.target.id==='portfolio-search'){S.query=e.target.value;renderPortfolios();}if(e.target.id==='source-search')renderSources();});
  $('#previous').addEventListener('click',()=>setSlide(S.slide-1));$('#next').addEventListener('click',()=>setSlide(S.slide+1));
  document.addEventListener('keydown',e=>{if(S.view!=='session'||dialog.open||e.altKey||e.ctrlKey||e.metaKey||/^(INPUT|TEXTAREA|SELECT|BUTTON)$/.test(e.target.tagName)||e.target.isContentEditable)return;if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();setSlide(e.key==='Home'?1:e.key==='End'?D.session.length:S.slide+(e.key==='ArrowRight'?1:-1));}});
  window.addEventListener('hashchange',readHash);window.addEventListener('popstate',readHash);
  $('#chapter-nav').innerHTML=[...new Set(D.session.map(s=>s.theme))].map(theme=>`<button data-jump="${D.session.find(s=>s.theme===theme).number}" data-theme="${esc(theme)}">${esc(theme)}</button>`).join('');
  $$('a[data-source-link]').forEach(a=>{const s=sourceMap[a.dataset.sourceLink];if(s)a.href=s.url;else a.textContent='Reference unavailable';});
  Object.keys(panelContent).forEach(renderPanel);readHash();secureLinks();
})();
